# Website title | Webサイトのタイトル
title: User
# Website description | Webサイトの説明
description: >-
  Here is a description of website.
# Language of the website | Webサイトの言語
lang: "en"
direction: "ltr" #ltr, rtl
# Web site protocol and host name | Webサイトのプロトコルとホスト名
url: https://example.com
# Select theme color | テーマカラーを選択
colorstyle: "blue" #blue, red, green
darkmode: "allow" #allow, true, false


# Create your profile. Each field can be left blank.
# プロフィールを作成します。項目は空白にもできます。
profile:
  # Your display name | 表示名
  name: User
  # URL of your profile icon | プロフィールアイコンのURL
  icon: "/assets/icon.png" 
  # If true, round the icon. | trueの場合、アイコンを丸くします。
  round-icon: true
  # URL of your header image | ヘッダー画像のURL
  header: "/assets/header.png" 
  # Your personal introduction | 自己紹介文
    Here is a description of you.
  bio: >-
  # Your contact info | 連絡先
  contact: 
    name: Email
    url: mailto:user@example.com
  pronouns: "they/them"
  # External links (e.g. social media). | 外部リンク (例、SNS)
  links:
    - name: X
      url: "https://x.com/x"
    - name: YouTube
      url: "https://youtube.com/@YouTube"
    - name: GitHub
      url: "https://github.com/github"


# Advanced settings
head:
  #https://example.com
  canonical: 
  #https://example.onion
  onion-location: 
  noindex: false
  ogp: true
  # Use profile icon if blank
  favicon: 
  siteicon: 

date-format: "%Y-%m-%d"
copyright: 
allow-image-select: false

home:
  show-excerpts: true
  subscribe-button: true
  subscribe-link: 

post:
  hide-profile: false
  backto: "/"
  highlight: true


# Text settings
text:
  paginate-back: "Back" #Back
  paginate-next: "Next" #Next
  subscribe: "Subscribe" #Subscribe


# Build settings

#theme: benjeto

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-paginate

# Paginate settings
# To use this, jekyll-paginate must be installed.
paginate: 20
paginate_path: "/pages/:num/"

exclude:
  - LICENSE.txt
  - README.md
  - README-ja.md
  - Gemfile
  - Gemfile.lock
  - Benjeto.gemspec

