# Website title.
title: User
# Website description.
description: >-
  Here is a description of website.
# Language of the website.
lang: "ar"
# Web site protocol and host name.
url: https://example.com
permalink: "/posts/:title/"


##### Build settings #####

feed:
  # Maximum number of posts in the feed.
  posts_limit: 20
  tags:
    path: "/tags/"
  categories:
    - articles
    - clips

## Pagenate v1
# Maximum number of posts to be displayed on home page.
# If blank, disable paginate.
#paginate: 10
#paginate_path: "/pages/:num/"

## Pagenate-v2
pagination:
  enabled: true
  # Maximum number of posts to be displayed on home page.
  per_page: 10
  permalink: '/pages/:num/'
  sort_reverse: true

defaults:
  - values:
      title: ""

sass:
  style: compressed

plugins:
  - jekyll-feed
  #- jekyll-paginate
  - jekyll-paginate-v2

exclude:
  - LICENSE.txt
  - README.md
  - README-ja.md
  - Gemfile
  - Gemfile.lock
  - benjeto-jekyll-theme.gemspec

