# Website title | Webサイトのタイトル
title: User
# Website description | Webサイトの説明
description: >
  Here is a description of website.
# Language of the website | Webサイトの言語
lang: en
# Web site protocol and host name | Webサイトのプロトコルとホスト名
url: https://example.com


# Create your profile. Each field can be left blank.
# プロフィールを作成します。項目は空白にもできます。
profile:
  # Your display name | 表示名
  name: User
  # URL of your profile icon | プロフィールアイコンのURL
  icon: "/assets/icon.png" 
  # If true, round the icon. | trueの場合、アイコンを丸くします。
  round-icon: true
  # Your personal introduction | 自己紹介文
  bio: >
    Here is a description of you.
  # Your email address | メールアドレス
  email: user@example.com
  # External links (e.g. social media). | 外部リンク (例、SNS)
  links:
    - name: X
      icon: 
      url: "https://x.com/x"
    - name: YouTube
      icon: 
      url: "https://youtube.com/@YouTube"
    - name: GitHub
      icon: 
      url: "https://github.com/github"


# Advanced settings
head:
  #https://example.com
  canonical: 
  #https://example.onion
  onion-location: 
  noindex: "false"
  ogp: "true"
  # Use profile icon if blank
  favicon: 
  siteicon: 

date-format: "%Y-%m-%d"
copyright: 

post:
  hide-profile: "false"
  hide-date: "false"


# Build settings
#theme: benjeto

plugins:
  - jekyll-feed

exclude:
  - LICENSE.txt
  - README.md
  - README-ja.md
  - Gemfile
  - Gemfile.lock
  - Benjeto.gemspec
