# Website title | Webサイトのタイトル
title: User
# Website description | Webサイトの説明
description: >-
  Here is a description of website.
# Language of the website | Webサイトの言語
lang: "en"
# Web site protocol and host name | Webサイトのプロトコルとホスト名
url: https://example.com
permalink: "/posts/:title/"


##### Build settings #####

feed:
  # Maximum number of posts in the feed
  posts_limit: 20
  tags:
    path: "/tags/"

# Maximum number of posts to be displayed on one home page.
# If blank, disable paginate.
paginate: 2
paginate_path: "/pages/:num/"

defaults:
  - values:
      title: ""

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-paginate

exclude:
  - LICENSE.txt
  - README.md
  - README-ja.md
  - Gemfile
  - Gemfile.lock
  - benjeto-jekyll-theme.gemspec

