# Website title | Webサイトのタイトル
title: User
# Website description | Webサイトの説明
description: >-
  Here is a description of website.
# Language of the website | Webサイトの言語
lang: "en"
direction: "ltr" #ltr, rtl
# Web site protocol and host name | Webサイトのプロトコルとホスト名
url: https://example.com
# Select theme color | テーマカラーを選択
colorstyle: "blue" #blue, red, green
darkmode: "allow" #allow, true, false


### Create your profile. Each field can be left blank. ###
### プロフィールを作成します。項目は空白にもできます。 ###
profile:
  # Your display name | 表示名
  name: User
  # URL of your profile icon | プロフィールアイコンのURL
  icon: "/assets/icon.png" 
  # If true, round the icon. | trueの場合、アイコンを丸くします。
  round-icon: true
  # URL of your header image | ヘッダー画像のURL
  header: "/assets/header.png" 
  # Your personal introduction | 自己紹介文
  bio: >-
    You can edit your profile in _config.yml.
  # Your pronouns | 代名詞
  pronouns: 
  # External links (e.g. social media). | 外部リンク (例、SNS)
  links:
    - name: X
      url: "https://x.com/x"
    - name: YouTube
      url: "https://youtube.com/@YouTube"
    - name: GitHub
      url: "https://github.com/github"
  # Your contact info | 連絡先
  contact: 
    name: Email
    url: mailto:user@example.com
  # Tip | 寄付
  # Example, GitHub Sponsor link : https://github.com/sponsors/github
  #          Patreon link        : https://www.patreon.com/patreon
  #          Bitcoin address     : bitcoin:1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa
  tip: 
    name: Tip
    url: 



##### Advanced settings #####

# Set the date format, default is YYYY-MM-DD
date-format: "%Y-%m-%d"
# If true, the images can be saved by right-clicking, etc.
allow-image-select: true

head:
  #https://example.com
  canonical: 
  #https://example.onion
  onion-location: 
  # Prevents search engines from indexing your website.
  noindex: false
  # If true, website previews will be displayed on social media, etc.
  ogp: true
  # Use profile icon if blank.
  favicon: 
  siteicon: 

footer: 
  copyright: "(c) 20XX User"
  # Hide the RSS subscribe button.
  subscribe-button: true

home:
  # If true, the titled post's excerpt will be displayed on the home page.
  show-excerpts: true
  # Hide the RSS subscribe button.
  subscribe-button: true
  # Maximum number of posts to display on the home when paginate is not used.
  # If blank, unlimited
  max-posts: 20

post:
  # Highlight color to code in the post
  highlight: true

feed:
  # Maximum number of posts in the feed
  posts_limit: 20

# Maximum number of posts to be displayed on one home page.
# If blank, disable paginate.
paginate: 20
paginate_path: "/pages/:num/"

# Text settings
text:
  paginate-back: "Back" #Back
  paginate-next: "Next" #Next
  subscribe: "Subscribe" #Subscribe



##### Build settings #####

defaults:
  - values:
      title: ""

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-paginate

exclude:
  - LICENSE.txt
  - README.md
  - README-ja.md
  - Gemfile
  - Gemfile.lock
  - benjeto-jekyll-theme.gemspec

