##### Website settings #####

# Copyright notice in footer.
copyright:

# If true, round the profile icon.
round_icon: true

# If true, the images can be saved by right-clicking, etc.
allow_image_select: true

head:
  # Prevents search engines from indexing your website.
  noindex: false
  # If true, website previews will be displayed on social media, etc.
  ogp: true
  # If ogp is true, you can set your X account ID starting with @.
  x_id: 
  # Use profile icon if blank.
  favicon: 
  siteicon: 
  # Add a feed link.
  feed: true
  custom_feed: 

home:
  # If true, the titled post's excerpt will be displayed on the home page.
  show_excerpts: true
  # Show the RSS subscribe button.
  subscribe_button: true
  # Maximum number of posts to display on the home when paginate is not used.
  # If blank, unlimited.
  max_posts: 20
  # Show the share button on the posts list.
  share_button: true
  # Tabs at home pages.
  # You need to create a dedicated page with "layout: home".
  # name and url are required, omitting feed will hide the subscribe button.
  tabs:
    - name: "All"
      url: "/"
      feed: "/feed.xml"
      description: >-
        All articles and clips
    - name: "Articles"
      description: >-
        All articles written by me
      url: "/category/articles/"
      feed: "/feed/articles.xml"
    - name: "Clips"
      description: >-
        Little notes or diaries
      url: "/category/clips/"
      feed: "/feed/clips.xml"
    - name: "Favorites"
      description: >-
        My favorite clips and articles
      url: "/tags/favorites/"
      feed: "/tags/favorites.xml"

post:
  # Show RSS subscribe button.
  subscribe_button: true
  # Show your profile in footer.
  footer_profile: "article" #true, false, article
  # Set the font on the article to serif.
  article_serif: false
  # Show the share button on the post.
  share_button: true

style: # Style settings are applied to the entire website.
  # Set darkmode. 
  darkmode: "allow" #allow, true, false
  # Highlight color to code in the post.
  highlight: true
  # Advanced settings.
  menu: true
  figure: true
  home_tab: true
  paginate: true
  app_box: false
  section_box: false

