##### Website settings #####
# Select theme color | テーマカラーを選択
colorstyle: "blue" #blue, red, green
# Set darkmode | ダークモードを設定
darkmode: "false" #allow, true, false
# Highlight color to code in the post
highlight: true

# If true, round the icon. | trueの場合、アイコンを丸くします。
round_icon: true

# Copyright notice in footer | フッターに著作権表示をする
copyright: 

# If true, the images can be saved by right-clicking, etc.
allow_image_select: true

head:
  # Prevents search engines from indexing your website.
  noindex: false
  # If true, website previews will be displayed on social media, etc.
  ogp: true
  # Use profile icon if blank.
  favicon: 
  siteicon: 

home:
  # If true, the titled post's excerpt will be displayed on the home page.
  show_excerpts: true
  # Show the RSS subscribe button.
  subscribe_button: true
  # Maximum number of posts to display on the home when paginate is not used.
  # If blank, unlimited
  max_posts: 20
  # Show the share button on the posts list
  share_button: true
  # Filter tab in home
  tabs:
    - name: "All"
      url: "/"
      feed: "/feed.xml"
    - name: "Articles"
      discription: >-
        All articles written by me
      url: "/category/articles/"
      feed: "/feed/articles.xml"
    - name: "Clips"
      discription: >-
        Little notes or diaries
      url: "/category/clips/"
      feed: "/feed/clips.xml"
    - name: "Favorite"
      discription: >-
        My favorite clips and articles
      url: "/tags/likes/"
      feed: "/tags/likes.xml"

post:
  # Show RSS subscribe button.
  subscribe_button: true
  # Show your profile in footer.
  footer_profile: "article" #true, false, article
  # Set the font on the article to serif
  article_serif: false
  # Show the share button on the post
  share_button: true

